name: Deploy
description: Deploy new image to ECS task definition
inputs:
  aws-access-key-id:
    required: true
    description: "AWS access key id"
  aws-secret-access-key:
    required: true
    description: "AWS access key"
  aws-account-id:
    required: true
    description: "AWS account id"
  cluster-name:
    required: true
    description: "Name of ECS cluster"
  service-name:
    required: true
    description: "Name of service"
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: eu-west-1

    - name: Deploy Amazon ECS task definition
      shell: bash
      run: docker run fabfuel/ecs-deploy:1.10.2 ecs cron ${{ inputs.cluster-name }} arn:aws:ecs:eu-west-1:${{ inputs.aws-account-id }}:task-definition/${{ inputs.service-name }} ${{ inputs.service-name }} --image main 431904215020.dkr.ecr.eu-west-1.amazonaws.com/${{ inputs.service-name }}:${{ github.sha }} --region eu-west-1 --access-key-id ${{ inputs.aws-access-key-id }} --secret-access-key ${{ inputs.aws-secret-access-key }}