name: Deploy
description: Deploy new image to ECS task definition
inputs:
  aws-access-key-id:
    required: true
    description: "AWS access key id"
  aws-secret-access-key:
    required: true
    description: "AWS access key"
  aws-account-id:
    required: true
    description: "AWS account id"
  cluster-name:
    required: true
    description: "Name of ECS cluster"
  service-name:
    required: true
    description: "Name of service"
  docker-registry:
    required: true
    description: "Registry where image is located"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: eu-west-1

    - id: short-sha
      shell: bash
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Deploy Amazon ECS task definition
      env:
        DOCKER_IMAGE: ${{ inputs.docker-registry }}/${{ inputs.service-name }}:${{ steps.short-sha.outputs.sha }}
      shell: bash
      run: docker run fabfuel/ecs-deploy:1.10.2 ecs cron ${{ inputs.cluster-name }} arn:aws:ecs:eu-west-1:${{ inputs.aws-account-id }}:task-definition/${{ inputs.service-name }} ${{ inputs.service-name }} --image main $DOCKER_IMAGE --region eu-west-1 --access-key-id ${{ inputs.aws-access-key-id }} --secret-access-key ${{ inputs.aws-secret-access-key }}
